info:
    serviceLinks:
        api-doc: "${route.name}/docs/index.html"
    dependencies:
        skatteetaten: "skatteetaten"

spring:
    profiles:
        active: local

logging:
    level:
      ske.aurora: INFO
      no.skatteetaten: INFO
      org:
        springframework: WARN
        apache.catalina: WARN
        hibernate: WARN

---
spring:
  profiles: local
  datasource:
    # id: 02150c29-6ab9-4917-bd56-1ba63d4f46d5"
    url: ${refapp.datasource.url:jdbc:oracle:thin:@uil0map-drivein-db02:1521/dbhotel}
    username: ${refapp.datasource.username:MFBDNLMIQTWTWNWEQOMLPAAPJDKSYV}
    password: ${refapp.datasource.password:qWieNxGpdFcjVOHPiaCTcmJqYdgYkk}


management:
    server.port: 8081


logging:
    pattern:
      console: "%d [%-9.9thread] %-5level %logger %X - %msg %n%rEx{full}"

